### ISSUE TITLE
Readme looks strange in pypi site

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-cli#42]
See: https://pypi.org/project/auger-cli/

**Comment by IgorFlint** [comment]
Firstly, I've figured out it was never displayed correctly, since the very first version:  https://pypi.org/project/auger-cli/0.1.0/ 

Next, I've searched for answer and there are bugs in wheel that reported to give the same issues.
As well as there are serveral warnings with our setup.py file, reported by `python setup.py ckeck -r -s`:
```running check
warning: Check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too

warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 15: Warning: Inline literal start-string without end-string.

error: Please correct your package.
```

So I'm gonna fix 'em

**Comment by IgorFlint** [comment]
Fixed in master, need check
